# Generated by Django 5.2.6 on 2025-11-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("RA_street_num", models.TextField()),
                ("RA_street_name", models.TextField()),
                ("RA_apt_num", models.TextField(blank=True)),
                ("RA_zip", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("date_of_res", models.DateField()),
                ("party_affiliation", models.TextField()),
                ("precinct_num", models.TextField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
