# Generated by Django 5.2.6 on 2025-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="join_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
