# Generated by Django 5.2.6 on 2025-09-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_alter_profile_join_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(max_length=90),
        ),
    ]
