# Generated by Django 5.2.6 on 2025-11-25 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("show", "Show"),
                            ("unknown", "Unkonwn"),
                        ],
                        default="unknown",
                    ),
                ),
                ("release_date", models.DateField()),
                ("poster_url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("season_ep", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="WatchListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("watching", "Watching"),
                            ("want_to_watch", "Want to watch"),
                            ("watched", "Watched"),
                        ],
                        default="want_to_watch",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.mediaitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EpisodeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_ep_watched", models.JSONField(blank=True, default=list)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.mediaitem",
                    ),
                ),
                (
                    "watchlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.watchlistentry",
                    ),
                ),
            ],
        ),
    ]
