# Generated by Django 5.2.6 on 2025-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodeprogress",
            name="season_ep_watched",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
