# Generated by Django 5.2.6 on 2025-12-08 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_episodeprogress_season_ep_watched"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("episode", models.IntegerField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Unrrated"),
                            (1, "Awful"),
                            (2, "Bad"),
                            (3, "Ok"),
                            (4, "Good"),
                            (5, "Great"),
                        ]
                    ),
                ),
                (
                    "watchlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ep_rating",
                        to="project.watchlistentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Unrrated"),
                            (1, "Awful"),
                            (2, "Bad"),
                            (3, "Ok"),
                            (4, "Good"),
                            (5, "Great"),
                        ]
                    ),
                ),
                (
                    "watchlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.watchlistentry",
                    ),
                ),
            ],
        ),
    ]
