# Generated by Django 5.2.6 on 2025-12-08 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_rateepisode_ratemedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodeprogress",
            name="media_item",
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("show", "Show"), ("unknown", "Unkonwn")],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ratemedia",
            name="watchlist_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="project.watchlistentry"
            ),
        ),
        migrations.AlterField(
            model_name="watchlistentry",
            name="media_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_entries",
                to="project.mediaitem",
            ),
        ),
        migrations.AlterField(
            model_name="watchlistentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("watching", "Watching"),
                    ("want_to_watch", "Want to watch"),
                    ("watched", "Watched"),
                ],
                default="want_to_watch",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="watchlistentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CommentEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("episode", models.IntegerField()),
                ("comment", models.CharField(max_length=250)),
                (
                    "watchlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ep_comment",
                        to="project.watchlistentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=250)),
                (
                    "watchlist_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_comment",
                        to="project.watchlistentry",
                    ),
                ),
            ],
        ),
    ]
