# Generated by Django 5.2.6 on 2025-12-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_episodeprogress_media_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("show", "Show"), ("unknown", "Unknown")],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rateepisode",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, "Unrated"),
                    (1, "Awful"),
                    (2, "Bad"),
                    (3, "Ok"),
                    (4, "Good"),
                    (5, "Great"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ratemedia",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, "Unrated"),
                    (1, "Awful"),
                    (2, "Bad"),
                    (3, "Ok"),
                    (4, "Good"),
                    (5, "Great"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="watchlistentry",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="rateepisode",
            unique_together={("watchlist_entry", "season", "episode")},
        ),
    ]
