# Generated by Django 5.2.6 on 2025-12-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_episodeprogress_watchlist_entry_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
