# Generated by Django 5.2.6 on 2025-12-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_userprofile_is_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlistentry",
            name="user",
        ),
    ]
