# Generated by Django 5.2.6 on 2025-12-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_remove_watchlistentry_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rateepisode",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rateepisode",
            name="watchlist_entry",
        ),
        migrations.DeleteModel(
            name="CommentEpisode",
        ),
        migrations.DeleteModel(
            name="RateEpisode",
        ),
    ]
